[package]
name = "tskit_rust"
version = "0.1.0"
authors = ["molpopgen <krthornt@uci.edu>"]
build = "build.rs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"
