[package]
name = "tskit_rust"
version = "0.1.0"
authors = ["molpopgen <krthornt@uci.edu>"]
build = "build.rs"
edition = "2018"
description = "rust interface to tskit"
license = "MIT"
homepage = "https://github.com/molpopgen/tskit_rust"
repository = "https://github.com/molpopgen/tskit_rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
libc = "0.2.81"

[dev-dependencies]
serde = {version = "1.0.118", features = ["derive"]}
bincode = "1.3.1"

[build-dependencies]
bindgen = "0.56.0"
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"
